#pragma once

// From glfw.h
#define RNDR_MOUSE_BUTTON_1         0
#define RNDR_MOUSE_BUTTON_2         1
#define RNDR_MOUSE_BUTTON_3         2
#define RNDR_MOUSE_BUTTON_4         3
#define RNDR_MOUSE_BUTTON_5         4
#define RNDR_MOUSE_BUTTON_6         5
#define RNDR_MOUSE_BUTTON_7         6
#define RNDR_MOUSE_BUTTON_8         7
#define RNDR_MOUSE_BUTTON_LAST      RNDR_MOUSE_BUTTON_8
#define RNDR_MOUSE_BUTTON_LEFT      RNDR_MOUSE_BUTTON_1
#define RNDR_MOUSE_BUTTON_RIGHT     RNDR_MOUSE_BUTTON_2
#define RNDR_MOUSE_BUTTON_MIDDLE    RNDR_MOUSE_BUTTON_3