# name: Windows Build

# on:
#   push:
#     branches:
#       - main
#   pull_request:
#     branches:
#       - main

# jobs:
#   build:

#     runs-on: windows-latest

#     steps:
#     - name: Checkout repository
#       uses: actions/checkout@v2

#     - name: Set up MSVC
#       uses: ilammy/msvc-dev-cmd@v1
#       with:
#         arch: x64

#     - name: Configure with CMake
#       run: cmake -B build -S .

#     - name: Build
#       run: cmake --build build --config Release

name: Windows Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: true  # Initialize and update submodules

    - name: Set up MSVC
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64

    - name: Create build directory
      run: mkdir build

    - name: Change to build directory and run CMake
      run: |
        cd build
        cmake -G "Visual Studio 17 2022" -A x64 -DCMAKE_BUILD_TYPE=Debug ..
        cmake --build . --config Debug
